# Generated by Django 4.2.16 on 2024-10-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('sent_date', models.DateTimeField()),
                ('receive_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailReader.emailaccount')),
            ],
        ),
    ]
